### ISSUE TITLE
FIX: The 3D mesh does not appear when one opens the AI tab for the first time.

### ISSUE THREAD

**Issue by ninamiolane** [geometric-intelligence/herbrain#9]
The 3D mesh does not appear when one opens the AI tab for the first time. It does appear when we click on the button that toggles between gestational week and hormones.

<img width="1784" alt="Screen Shot 2024-12-19 at 11 42 49 AM" src="https://github.com/user-attachments/assets/b2b0c0d5-e601-4e17-aeca-fd3a71d1b0da" />

**Comment by ninamiolane** [comment]
Possibly related to:

<img width="1780" alt="Screen Shot 2024-12-19 at 11 54 49 AM" src="https://github.com/user-attachments/assets/2b0adcec-2450-4eba-931f-c785eaa099b2" />

**Comment by luisfpereira** [comment]
This is related with latest version of `sklearn` ([1.6.0](https://pypi.org/project/scikit-learn/1.6.0/)).
Fixing it.

If you need to run it meanwhile, install `sklearn==1.5.2`.

**Comment by luisfpereira** [comment]
Closing as https://github.com/luisfpereira/polpo/commit/a5b908abaf9065303cd73a9d821e2d60cf6a93c1 solves the issue. @ninamiolane , please reinstall `polpo` and, if the problem persists, reopen the issue.
